### PR TITLE
Add order direction constants

### PR DESCRIPTION
**Pull request by jasonmoo**
Hey just added some backwards compatible constants for order direction that make the code a bit more explicit.  Feel free to merge.

Thanks for the lib.

### CODE REVIEW

**Comment by SebastiaanKlippert** [comment]
Thanks for the contribution. I like the idea, but this would be a breaking change for the current users.
I would need to introduce versions before I can merge this. So I am not sure I want to do this now. 
If we find a bug we cannot make existing users update without having to change all their AddOrder calls.
I would prefer a new method and keep the existing one.

**Comment by jasonmoo** [comment]
Hi.  This is actually backwards compatible.  Since the `type Direction bool` allows a bool to be passed in the function call.  I have run the test suite using both bare `bool`s and the `Direction` constants.

**Comment by SebastiaanKlippert** [comment]
I am sorry, I should have looked at it better, I was at work and took a quick look with only half of my attention focused at the request.
I saw the tests passed. But was confused because the test file was also changed, which made me think we had to change parameters.

Thanks again for the pull request, I agree this makes the calling code more clear!

**Comment by jasonmoo** [comment]
You bet.  Thanks for the lib!

**Pull request merged**
